[package]
authors = ["Josh Palmer <jpalmerwatkins@gmail.com>"]
edition = "2018"
name = "antigen_components"
version = "0.1.0"

[features]
default = ["egui"]

[dependencies]
deebs = {path = "../deebs"}
egui = {version = "0.12.0", optional = true}
